### ISSUE TITLE
Wrong G-Code output if text input size is exactly 100 bytes

### ISSUE THREAD

**Issue by koppi** [Andy1978/hf2gcode#5]
Wrong G-Code output if text input size is exactly 100 bytes:
see Video: https://www.youtube.com/watch?v=hL--jb6tRf0

**Comment by Andy1978** [comment]
Yes, there was a bug: https://github.com/Andy1978/hf2gcode/commit/668214574c8c1f447589a200911971eb7a2d1247

Please try again with the latest version

**Comment by koppi** [comment]
:+1:

![screenshot from 2016-04-23 22-16-58](https://cloud.githubusercontent.com/assets/9458631/14763779/40c422c8-09a1-11e6-94db-7d90544604af.png)
