### ISSUE TITLE
multi-line text: x offset should apply to each line

### ISSUE THREAD

**Issue by ec1oud** [Andy1978/hf2gcode#7]
If I try to generate g-code from an input file with line breaks, the x offset only indents the first line, but not the following lines.

e.g. hf2gcode --font=scripts -o out.nc -i in.txt -s 0.3 -y 100 -x 100

**Comment by Andy1978** [comment]
Hi ec1oud,
is this issue fixed with https://github.com/Andy1978/hf2gcode/commit/e58f52ae6e1c0ce383483f8a8b0a0319ca5df8c7 ?

**Comment by Andy1978** [comment]
No reply but I guess this was fixed with the mentioned cset

**Comment by ec1oud** [comment]
Yes that fixed it, thanks!

If I use -s with a negative number, I can make it print the text upside-down, but then the lines print backwards because line spacing is going the same direction as the scale.  ;-)  But that's not very surprising and not a big problem.
